
bot.name = DVSTESTINGBot
bot.token = 5824348548:AAFNTYsg5g3hnAC58Q5k0sY-mb1Uk8PJ4PI
service.file_info.uri=https://api.telegram.org/bot5824348548:AAFNTYsg5g3hnAC58Q5k0sY-mb1Uk8PJ4PI/getFile?file_id=
service.file_storage.uri=https://api.telegram.org/file/bot5824348548:AAFNTYsg5g3hnAC58Q5k0sY-mb1Uk8PJ4PI/

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/example
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql: false


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username= mailnotificationbot63@gmail.com
spring.mail.password= vorisdxvgreawsvq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


#sheduler
cron.deleteUser= 0 0 10 ? * MON
cron.finishVerification= 0 0 10 * * *
cron.userActivate= 0 30 * * * *
